from enum import StrEnum


class BoxStatus(StrEnum):
    REGISTERING='REGISTERING'; DRYING='DRYING'; READY='READY'; RESERVED='RESERVED'; RETRIEVAL_PLANNED='RETRIEVAL_PLANNED'; IN_TRANSIT='IN_TRANSIT'; AT_PICKING='AT_PICKING'; RETURN_PLANNED='RETURN_PLANNED'; RETURNING='RETURNING'; STORED='STORED'; EMPTY='EMPTY'; QUARANTINED='QUARANTINED'; FAULTED='FAULTED'

class SlotType(StrEnum):
    STORAGE='STORAGE'; BUFFER='BUFFER'; QUARANTINE='QUARANTINE'; ENTRY_PICKING='ENTRY_PICKING'; MAINTENANCE='MAINTENANCE'

class SlotStatus(StrEnum):
    FREE='FREE'; OCCUPIED='OCCUPIED'; RESERVED='RESERVED'; RESERVED_FOR_RETURN='RESERVED_FOR_RETURN'; BLOCKED='BLOCKED'; MAINTENANCE='MAINTENANCE'; DISABLED='DISABLED'

class ProductionRequestStatus(StrEnum):
    PENDING='PENDING'; PLANNING='PLANNING'; SIMULATING='SIMULATING'; APPROVED='APPROVED'; EXECUTING='EXECUTING'; COMPLETED='COMPLETED'; PARTIALLY_FULFILLABLE='PARTIALLY_FULFILLABLE'; REJECTED='REJECTED'; FAILED='FAILED'; CANCELLED='CANCELLED'

class PlanStatus(StrEnum):
    DRAFT='DRAFT'; SIMULATED='SIMULATED'; APPROVED='APPROVED'; EXECUTING='EXECUTING'; COMPLETED='COMPLETED'; FAILED='FAILED'

class RobotTaskType(StrEnum):
    STORE_BOX='STORE_BOX'; RETRIEVE_BOX='RETRIEVE_BOX'; DELIVER_TO_PICKING='DELIVER_TO_PICKING'; RETURN_BOX='RETURN_BOX'; MOVE_TO_BUFFER='MOVE_TO_BUFFER'; MOVE_FROM_BUFFER='MOVE_FROM_BUFFER'; HOME='HOME'; RECOVERY='RECOVERY'

class RobotTaskStatus(StrEnum):
    QUEUED='QUEUED'; DISPATCHED='DISPATCHED'; RUNNING='RUNNING'; COMPLETED='COMPLETED'; FAILED='FAILED'; CANCELLED='CANCELLED'; INTERRUPTED='INTERRUPTED'

class FaultType(StrEnum):
    ESTOP='ESTOP'; X_AXIS_FAULT='X_AXIS_FAULT'; Z_AXIS_FAULT='Z_AXIS_FAULT'; FORK_FAULT='FORK_FAULT'; SLOT_BLOCKED='SLOT_BLOCKED'; BOX_NOT_DETECTED='BOX_NOT_DETECTED'; POSITION_MISMATCH='POSITION_MISMATCH'; LOW_CV_CONFIDENCE='LOW_CV_CONFIDENCE'; QUANTITY_MISMATCH='QUANTITY_MISMATCH'; WAREHOUSE_FULL='WAREHOUSE_FULL'

class AlertSeverity(StrEnum):
    INFO='INFO'; WARNING='WARNING'; CRITICAL='CRITICAL'

class PickingStationStatus(StrEnum):
    FREE='FREE'; OCCUPIED='OCCUPIED'; WAITING_CONFIRMATION='WAITING_CONFIRMATION'; FAULT='FAULT'
