import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {get,post} from '../api/client'
import {Card,PageHeader,Notice,Metric} from '../components/Common'
export default function Configuration(){
 const qc=useQueryClient();const cfg=useQuery({queryKey:['config'],queryFn:()=>get<any>('/configuration')});const demo=useQuery({queryKey:['demoConfig'],queryFn:()=>get<any>('/demo/status')})
 const advance=useMutation({mutationFn:(hours:number)=>post('/simulation/time/advance',{hours}),onSuccess:()=>qc.invalidateQueries()});const init=useMutation({mutationFn:()=>post('/warehouse/initialize'),onSuccess:()=>qc.invalidateQueries()});const reset=useMutation({mutationFn:()=>post('/demo/reset'),onSuccess:()=>qc.invalidateQueries()})
 return <><PageHeader title="System Configuration" subtitle="Demo controls and read-only runtime configuration. Geometry and robot timing stay external to business logic."/>
 <div className="metrics"><Metric label="Core types" value={demo.data?.core_types??'—'}/><Metric label="Seeded boxes" value={demo.data?.boxes??'—'}/><Metric label="Ready" value={demo.data?.ready_boxes??'—'} tone="good"/><Metric label="Drying" value={demo.data?.drying_boxes??'—'} tone="warn"/><Metric label="Clock" value={demo.data?.clock?.mode==='SIMULATION_TIME'?'SIM':'REAL'}/></div>
 <div className="grid2"><Card title="DEMO CLOCK"><p className="cardExplain">Advance the application clock to test the 24-hour drying rule instantly.</p><div className="actions"><button onClick={()=>advance.mutate(1)}>+1 hour</button><button onClick={()=>advance.mutate(6)}>+6 hours</button><button onClick={()=>advance.mutate(24)}>+24 hours</button></div></Card><Card title="DEMO DATA"><Notice tone="info" title="The application auto-seeds a fresh database"><span>Use reset whenever you want to return to the deterministic acceptance-test state.</span></Notice><button className="dangerOutline" onClick={()=>reset.mutate()} disabled={reset.isPending}>Reset all demo data</button></Card><Card title="WAREHOUSE GEOMETRY"><p className="cardExplain">Initialize only missing physical locations from <code>config/warehouse.yaml</code>.</p><button className="secondary" onClick={()=>init.mutate()}>Initialize missing slots</button></Card></div>
 <Card title="ACTIVE CONFIGURATION"><pre className="result configResult">{cfg.data?JSON.stringify(cfg.data,null,2):'Loading...'}</pre></Card></>}
